import { CollegeDetail } from "@/types/college";

export const COLLEGE_DETAILS: Record<string, CollegeDetail> = {
  mit: {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA",
    city: "Cambridge",
    state: "MA",
    type: "private",
    ranking: 1,
    rating: 4.9,
    tuition: 57986,
    acceptanceRate: 0.04,
    enrollment: 11574,
    founded: 1861,
    satRange: [1510, 1580],
    color: "#A31F34",
    description: "A world-renowned research university known for science, engineering, and technology. MIT drives innovation across virtually every field, producing Nobel laureates, astronauts, and CEOs who shape the future.",
    programs: ["Computer Science", "Engineering", "Mathematics", "Physics", "Architecture"],
    tags: ["Research", "STEM", "Urban", "Ivy-Adjacent"],
    website: "https://web.mit.edu",
    email: "admissions@mit.edu",
    phone: "+1 (617) 253-1000",
    accreditation: ["NECHE", "ABET", "AACSB"],
    facilities: ["Research Labs", "Innovation Center", "Olympic Pool", "Concert Hall", "Medical Center", "Observatory", "Nuclear Reactor", "Wind Tunnel"],
    scholarships: [
      { name: "MIT Need-Based Aid", amount: 57986, criteria: "Based entirely on demonstrated financial need" },
      { name: "THINK Grant", amount: 8000, criteria: "For entrepreneurial student projects" },
      { name: "Lemelson-MIT Prize", amount: 15000, criteria: "For inventive student engineers" },
    ],
    courses: [
      {
        id: "cs-bs",
        name: "Computer Science & Engineering",
        department: "EECS",
        duration: "4 years",
        degree: "B.S.",
        tuition: 57986,
        seats: 280,
        description: "MIT's flagship CS program prepares students to tackle the world's hardest technical problems through rigorous theory and hands-on research.",
        highlights: ["Turing Award alumni faculty", "Access to CSAIL lab", "Industry projects from Day 1", "AI/ML specialization tracks"],
      },
      {
        id: "aero-bs",
        name: "Aerospace Engineering",
        department: "AeroAstro",
        duration: "4 years",
        degree: "B.S.",
        tuition: 57986,
        seats: 120,
        description: "A comprehensive program covering aeronautics, astronautics, and space systems design with access to NASA-affiliated research centers.",
        highlights: ["NASA research partnerships", "Student satellite program", "Wind tunnel lab access", "Flight simulation"],
      },
      {
        id: "phys-phd",
        name: "Physics",
        department: "Physics",
        duration: "5 years",
        degree: "Ph.D.",
        tuition: 0,
        seats: 60,
        description: "A fully-funded doctoral program in theoretical and experimental physics, consistently ranked #1 globally.",
        highlights: ["Full tuition + stipend", "Nobel laureate mentors", "Particle physics lab", "Quantum computing research"],
      },
      {
        id: "mba",
        name: "Sloan MBA",
        department: "Sloan School",
        duration: "2 years",
        degree: "M.B.A.",
        tuition: 80400,
        seats: 400,
        description: "MIT Sloan's MBA program is built on rigorous analytics and a strong emphasis on innovation and entrepreneurship.",
        highlights: ["$200B+ alumni network", "MIT startup ecosystem", "Global lab immersions", "Action learning projects"],
      },
      {
        id: "arch-m",
        name: "Architecture",
        department: "Architecture",
        duration: "2 years",
        degree: "M.Arch.",
        tuition: 57986,
        seats: 50,
        description: "A graduate architecture program that integrates computational design, sustainability, and urban theory.",
        highlights: ["Computation lab", "Fabrication studios", "Global studio travel", "Collaboration with Media Lab"],
      },
      {
        id: "bio-bs",
        name: "Biological Engineering",
        department: "Biological Engineering",
        duration: "4 years",
        degree: "B.S.",
        tuition: 57986,
        seats: 90,
        description: "An interdisciplinary program at the intersection of biology, engineering, and medicine with strong research opportunities.",
        highlights: ["Whitehead Institute access", "Synthetic biology lab", "Pre-med pathway", "Industry co-ops"],
      },
    ],
    placement: {
      year: 2024,
      placementRate: 0.97,
      avgPackage: 145000,
      highestPackage: 580000,
      topRecruiters: ["Google", "Meta", "Apple", "SpaceX", "McKinsey", "Jane Street", "Citadel", "Amazon", "Microsoft", "Lockheed Martin"],
      sectors: [
        { name: "Technology",  percent: 42, color: "#3B82F6" },
        { name: "Finance",     percent: 18, color: "#8B5CF6" },
        { name: "Engineering", percent: 16, color: "#10B981" },
        { name: "Consulting",  percent: 12, color: "#F59E0B" },
        { name: "Research",    percent: 8,  color: "#EF4444" },
        { name: "Other",       percent: 4,  color: "#94A3B8" },
      ],
    },
    reviews: [
      {
        id: "r1",
        author: "Priya Nair",
        avatar: "PN",
        avatarColor: "#6366F1",
        batch: "Class of 2024",
        program: "Computer Science & Engineering",
        rating: 5,
        date: "March 2024",
        title: "Hardest four years of my life — completely worth it",
        body: "MIT is demanding in ways that feel almost surreal at first. The psets will break you, the pace is relentless, and imposter syndrome is constant. But the peers, the research access, and the way problems are framed here completely changed how I think. I've shipped code used by millions, published a paper as a junior, and have two job offers with comp I couldn't have imagined at 18.",
        pros: ["World-class research access", "Brilliant and driven peers", "Alumni network is unreal", "Strong mental health support (they've improved a lot)"],
        cons: ["Workload is genuinely brutal", "Boston winters hit different", "Social life requires effort to build"],
        helpful: 247,
      },
      {
        id: "r2",
        author: "James Whitfield",
        avatar: "JW",
        avatarColor: "#0EA5E9",
        batch: "Class of 2023",
        program: "Aerospace Engineering",
        rating: 5,
        date: "January 2024",
        title: "If you want to work on spacecraft, there's nowhere better",
        body: "I came in wanting to work on real rockets and I left with an offer from SpaceX and a paper in AIAA. The AeroAstro department gives undergrads access to labs, hardware, and mentorship that doctoral students at other schools would envy. The culture is collaborative despite the competition — everyone wants everyone else to succeed.",
        pros: ["Hands-on hardware access from year 1", "NASA and SpaceX collaborations", "Small department = personal attention", "UROP program is exceptional"],
        cons: ["Limited campus green space", "Housing is expensive", "Department can be siloed from others"],
        helpful: 189,
      },
      {
        id: "r3",
        author: "Sofia Mendez",
        avatar: "SM",
        avatarColor: "#EC4899",
        batch: "MBA 2023",
        program: "Sloan MBA",
        rating: 4,
        date: "December 2023",
        title: "Best MBA for tech + entrepreneurship, not for traditional consulting",
        body: "Sloan is transformative if you're interested in tech, startups, or data-driven businesses. The curriculum is analytically rigorous and the MIT ecosystem gives you access to cutting-edge research. If you're gunning for McKinsey or Goldman, Harvard or Wharton may serve you better — but for building something at the frontier, Sloan is unmatched.",
        pros: ["Incredible startup ecosystem", "Strong VC and tech alumni", "Rigorous analytical foundation", "Action Learning courses are superb"],
        cons: ["Smaller alumni network than HBS/Wharton for finance", "Campus can feel isolated", "Work-life balance is tough to maintain"],
        helpful: 134,
      },
      {
        id: "r4",
        author: "Kenji Ota",
        avatar: "KO",
        avatarColor: "#F59E0B",
        batch: "Class of 2022",
        program: "Physics",
        rating: 5,
        date: "October 2023",
        title: "The Ph.D. experience is what you make it — I made it amazing",
        body: "The physics department has Nobel laureates who actually teach courses and take on students. My advisor was on the Nobel committee and still made time for weekly 1:1s. The stipend is livable, the research is cutting-edge, and the network of MIT physicists you build is for life. Be warned: the qualifier exam is no joke.",
        pros: ["Nobel laureate faculty who actually mentor", "Fully funded with living stipend", "Cutting-edge experimental facilities", "Collaborative culture between labs"],
        cons: ["Qualifier exam is extremely difficult", "PhD timeline can stretch", "Cambridge housing is extremely expensive"],
        helpful: 98,
      },
    ],
    overallRatings: {
      academics:  4.9,
      campus:     4.3,
      faculty:    4.8,
      placements: 4.9,
      value:      4.2,
    },
  },

  stanford: {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA",
    city: "Stanford",
    state: "CA",
    type: "private",
    ranking: 2,
    rating: 4.8,
    tuition: 56169,
    acceptanceRate: 0.04,
    enrollment: 17249,
    founded: 1885,
    satRange: [1500, 1570],
    color: "#8C1515",
    description: "A leading research university in the heart of Silicon Valley, known for entrepreneurship, innovation, and a culture that encourages students to change the world.",
    programs: ["Computer Science", "Business", "Engineering", "Medicine", "Law"],
    tags: ["Research", "Entrepreneurship", "Silicon Valley", "STEM"],
    website: "https://www.stanford.edu",
    email: "admission@stanford.edu",
    phone: "+1 (650) 723-2300",
    accreditation: ["WASC", "ABET", "AACSB", "ABA"],
    facilities: ["d.school", "StartX Accelerator", "SLAC Lab", "Hoover Tower", "Cantor Arts Center", "Dish Trail", "Medical Center", "Anderson Collection"],
    scholarships: [
      { name: "Knight-Hennessy Scholars", amount: 100000, criteria: "Graduate study - leadership and civic purpose" },
      { name: "Stanford Need-Based Aid", amount: 56169, criteria: "Families earning under $150k pay zero tuition" },
      { name: "VPUE Research Grant", amount: 5000, criteria: "Undergraduate research funding" },
    ],
    courses: [
      {
        id: "cs-bs-s",
        name: "Computer Science",
        department: "Computer Science",
        duration: "4 years",
        degree: "B.S.",
        tuition: 56169,
        seats: 300,
        description: "Stanford CS combines deep theory with practical applications, with unrivaled access to Silicon Valley's tech ecosystem.",
        highlights: ["Faculty include Google/AI founders", "CS+X interdisciplinary tracks", "StartX student startup program", "Strong AI/HCI research"],
      },
      {
        id: "gbs",
        name: "Graduate School of Business",
        department: "GSB",
        duration: "2 years",
        degree: "M.B.A.",
        tuition: 78000,
        seats: 420,
        description: "The #1 MBA in the world — Stanford GSB produces more unicorn founders than any other program.",
        highlights: ["Most VC-backed alumni", "Silicon Valley immersion", "Change Lives, Change Organizations, Change the World", "Small cohort, high touch"],
      },
      {
        id: "mech-bs",
        name: "Mechanical Engineering",
        department: "ME",
        duration: "4 years",
        degree: "B.S.",
        tuition: 56169,
        seats: 180,
        description: "A rigorous engineering program with deep design, robotics, and manufacturing tracks.",
        highlights: ["d.school design thinking", "Robotics lab", "Product Realization Lab", "Industry senior capstone"],
      },
      {
        id: "law-jd",
        name: "Juris Doctor",
        department: "Law School",
        duration: "3 years",
        degree: "J.D.",
        tuition: 65000,
        seats: 180,
        description: "The most selective law school in the nation, known for public interest law and Silicon Valley IP practice.",
        highlights: ["Lowest student-faculty ratio of T14", "Supreme Court clerkship placements", "Startup/IP law specialization", "Loan repayment assistance"],
      },
    ],
    placement: {
      year: 2024,
      placementRate: 0.96,
      avgPackage: 152000,
      highestPackage: 620000,
      topRecruiters: ["Google", "Apple", "McKinsey", "Sequoia Capital", "a16z", "Stripe", "OpenAI", "Meta", "Palantir", "Snowflake"],
      sectors: [
        { name: "Technology",     percent: 48, color: "#3B82F6" },
        { name: "Finance/VC",     percent: 20, color: "#8B5CF6" },
        { name: "Consulting",     percent: 14, color: "#F59E0B" },
        { name: "Entrepreneurship", percent: 10, color: "#10B981" },
        { name: "Research",       percent: 5,  color: "#EF4444" },
        { name: "Other",          percent: 3,  color: "#94A3B8" },
      ],
    },
    reviews: [
      {
        id: "sr1",
        author: "Alex Chen",
        avatar: "AC",
        avatarColor: "#8C1515",
        batch: "Class of 2023",
        program: "Computer Science",
        rating: 5,
        date: "February 2024",
        title: "The culture of ambition is contagious",
        body: "At Stanford everyone is building something. My roommate started a company sophomore year. My TA was a YC founder. The culture is relentlessly optimistic about technology and its ability to change the world. CS curriculum is excellent and the professors are literally the people who built the internet.",
        pros: ["Silicon Valley access is unmatched", "Entrepreneurial culture", "Beautiful campus and weather", "Amazing cross-disciplinary opportunities"],
        cons: ["Housing is outrageously expensive", "Can feel like a tech bubble", "Grade deflation in some departments"],
        helpful: 312,
      },
      {
        id: "sr2",
        author: "Maya Johnson",
        avatar: "MJ",
        avatarColor: "#0EA5E9",
        batch: "GSB 2023",
        program: "MBA",
        rating: 5,
        date: "January 2024",
        title: "Worth every penny if you're going into tech or starting something",
        body: "GSB is a transformational experience. The cohort is extraordinary, the curriculum challenges you in unexpected ways, and the alumni network opens doors that simply don't exist otherwise. I came in wanting to join a startup and left having started one — with GSB connections as my first investors.",
        pros: ["Best entrepreneurship ecosystem", "Diverse and brilliant cohort", "Generous financial aid", "Lifelong alumni relationships"],
        cons: ["Extremely hard to get in", "Bay Area cost of living", "Less strong for traditional finance roles"],
        helpful: 201,
      },
    ],
    overallRatings: {
      academics:  4.8,
      campus:     4.9,
      faculty:    4.7,
      placements: 4.9,
      value:      4.1,
    },
  },

  "uc-berkeley": {
    id: "uc-berkeley",
    name: "UC Berkeley",
    location: "Berkeley, CA",
    city: "Berkeley",
    state: "CA",
    type: "public",
    ranking: 4,
    rating: 4.6,
    tuition: 14312,
    acceptanceRate: 0.14,
    enrollment: 45057,
    founded: 1868,
    satRange: [1310, 1530],
    color: "#003262",
    description: "One of the world's great public universities, Berkeley combines rigorous academics with a tradition of activism and a powerful network in Silicon Valley and beyond.",
    programs: ["Computer Science", "Engineering", "Business", "Law", "Social Sciences"],
    tags: ["Public Ivy", "Research", "Diversity", "Bay Area"],
    website: "https://www.berkeley.edu",
    email: "admissions@berkeley.edu",
    phone: "+1 (510) 642-6000",
    accreditation: ["WASC", "ABET", "AACSB"],
    facilities: ["Lawrence Hall of Science", "Bancroft Library", "Memorial Stadium", "Botanical Garden", "Space Sciences Lab", "Student Health Center", "RSF Recreation"],
    scholarships: [
      { name: "Berkeley Financial Aid", amount: 14312, criteria: "Need-based, 34% of students receive aid" },
      { name: "Regents & Chancellor's Scholarship", amount: 20000, criteria: "Top 1% of admitted students, merit-based" },
      { name: "Cal Grant", amount: 9084, criteria: "California residents with financial need" },
    ],
    courses: [
      {
        id: "eecs-bs",
        name: "Electrical Engineering & CS",
        department: "EECS",
        duration: "4 years",
        degree: "B.S.",
        tuition: 14312,
        seats: 350,
        description: "Berkeley EECS is the crown jewel of public CS education — rigorous, research-oriented, and deeply connected to industry.",
        highlights: ["Sky Computing Lab", "RISC-V architecture invented here", "Strong industry recruiting", "Top public CS program nationally"],
      },
      {
        id: "haas-mba",
        name: "Haas MBA",
        department: "Haas School of Business",
        duration: "2 years",
        degree: "M.B.A.",
        tuition: 58000,
        seats: 285,
        description: "A top-10 MBA with a distinctive culture centered on confidence without attitude, creativity, and sustainability.",
        highlights: ["Distinctive culture principles", "Strong Bay Area network", "Social impact focus", "Part-time/Evening program available"],
      },
      {
        id: "data-sci",
        name: "Data Science",
        department: "Division of Computing, Data Science, and Society",
        duration: "4 years",
        degree: "B.A.",
        tuition: 14312,
        seats: 200,
        description: "Berkeley's interdisciplinary data science program blends statistics, CS, and domain expertise with real-world projects.",
        highlights: ["Data 8 — most enrolled course in Berkeley history", "Industry capstone projects", "Human context and ethics focus", "Strong industry placement"],
      },
    ],
    placement: {
      year: 2024,
      placementRate: 0.93,
      avgPackage: 128000,
      highestPackage: 490000,
      topRecruiters: ["Google", "Meta", "Apple", "Salesforce", "LinkedIn", "Lyft", "Airbnb", "McKinsey", "Goldman Sachs", "Tesla"],
      sectors: [
        { name: "Technology",  percent: 50, color: "#3B82F6" },
        { name: "Finance",     percent: 15, color: "#8B5CF6" },
        { name: "Consulting",  percent: 12, color: "#F59E0B" },
        { name: "Nonprofits",  percent: 10, color: "#10B981" },
        { name: "Research",    percent: 8,  color: "#EF4444" },
        { name: "Other",       percent: 5,  color: "#94A3B8" },
      ],
    },
    reviews: [
      {
        id: "br1",
        author: "Daniel Park",
        avatar: "DP",
        avatarColor: "#003262",
        batch: "Class of 2024",
        program: "EECS",
        rating: 5,
        date: "April 2024",
        title: "Best value degree in the country. Full stop.",
        body: "Berkeley EECS at in-state tuition is the most insane deal in education. I had Google, Meta, and Stripe offers before graduation, and my total debt was near zero thanks to grants. The coursework is harder than most private schools, the research opportunities are real, and the Bay Area network is second only to Stanford.",
        pros: ["Incredible value for in-state", "Strong research and industry ties", "Diverse and motivated student body", "Berkeley brand opens every door"],
        cons: ["Large class sizes in lower-division", "Competitive and can be stressful", "Housing near campus is brutally expensive"],
        helpful: 289,
      },
    ],
    overallRatings: {
      academics:  4.6,
      campus:     4.4,
      faculty:    4.5,
      placements: 4.6,
      value:      4.9,
    },
  },
};

// Fallback detail builder for colleges not explicitly defined
export function getCollegeDetail(id: string): CollegeDetail | null {
  if (COLLEGE_DETAILS[id]) return COLLEGE_DETAILS[id];
  return null;
}
