import { College } from "@/types/college";

export const MOCK_COLLEGES: College[] = [
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA",
    city: "Cambridge",
    state: "MA",
    type: "private",
    ranking: 1,
    rating: 4.9,
    tuition: 57986,
    acceptanceRate: 0.04,
    enrollment: 11574,
    founded: 1861,
    satRange: [1510, 1580],
    color: "#A31F34",
    description: "A world-renowned research university known for science, engineering, and technology. MIT drives innovation across virtually every field.",
    programs: ["Computer Science", "Engineering", "Mathematics", "Physics", "Architecture"],
    tags: ["Research", "STEM", "Urban", "Ivy-Adjacent"],
  },
  {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA",
    city: "Stanford",
    state: "CA",
    type: "private",
    ranking: 2,
    rating: 4.8,
    tuition: 56169,
    acceptanceRate: 0.04,
    enrollment: 17249,
    founded: 1885,
    satRange: [1500, 1570],
    color: "#8C1515",
    description: "A leading research university in the heart of Silicon Valley, known for entrepreneurship and innovation.",
    programs: ["Computer Science", "Business", "Engineering", "Medicine", "Law"],
    tags: ["Research", "Entrepreneurship", "Silicon Valley", "STEM"],
  },
  {
    id: "harvard",
    name: "Harvard University",
    location: "Cambridge, MA",
    city: "Cambridge",
    state: "MA",
    type: "private",
    ranking: 3,
    rating: 4.9,
    tuition: 54269,
    acceptanceRate: 0.03,
    enrollment: 23731,
    founded: 1636,
    satRange: [1460, 1580],
    color: "#A51C30",
    description: "The oldest university in the United States, Harvard has produced more heads of state, billionaires, and Nobel laureates than any other institution.",
    programs: ["Law", "Medicine", "Business", "Economics", "Political Science"],
    tags: ["Ivy League", "Research", "Prestige", "Liberal Arts"],
  },
  {
    id: "uc-berkeley",
    name: "UC Berkeley",
    location: "Berkeley, CA",
    city: "Berkeley",
    state: "CA",
    type: "public",
    ranking: 4,
    rating: 4.6,
    tuition: 14312,
    acceptanceRate: 0.14,
    enrollment: 45057,
    founded: 1868,
    satRange: [1310, 1530],
    color: "#003262",
    description: "One of the top public universities in the world with exceptional research programs and a vibrant campus culture.",
    programs: ["Computer Science", "Engineering", "Business", "Law", "Social Sciences"],
    tags: ["Public Ivy", "Research", "Diversity", "Bay Area"],
  },
  {
    id: "princeton",
    name: "Princeton University",
    location: "Princeton, NJ",
    city: "Princeton",
    state: "NJ",
    type: "private",
    ranking: 5,
    rating: 4.8,
    tuition: 55240,
    acceptanceRate: 0.04,
    enrollment: 8474,
    founded: 1746,
    satRange: [1450, 1570],
    color: "#FF6F00",
    description: "An Ivy League research university renowned for undergraduate teaching, with a no-loan financial aid policy.",
    programs: ["Mathematics", "Physics", "Economics", "Computer Science", "Engineering"],
    tags: ["Ivy League", "Research", "Small Campus", "Prestige"],
  },
  {
    id: "yale",
    name: "Yale University",
    location: "New Haven, CT",
    city: "New Haven",
    state: "CT",
    type: "private",
    ranking: 6,
    rating: 4.8,
    tuition: 57700,
    acceptanceRate: 0.05,
    enrollment: 13609,
    founded: 1701,
    satRange: [1460, 1570],
    color: "#00356B",
    description: "A world-class Ivy League institution known for its strong programs in law, drama, and the liberal arts.",
    programs: ["Law", "Drama", "Political Science", "Economics", "History"],
    tags: ["Ivy League", "Liberal Arts", "Arts & Culture", "Prestige"],
  },
  {
    id: "columbia",
    name: "Columbia University",
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "private",
    ranking: 12,
    rating: 4.7,
    tuition: 63530,
    acceptanceRate: 0.04,
    enrollment: 35000,
    founded: 1754,
    satRange: [1470, 1570],
    color: "#003594",
    description: "An Ivy League university in the heart of Manhattan, offering unmatched access to New York City's cultural and professional ecosystem.",
    programs: ["Journalism", "Law", "Business", "Engineering", "Film"],
    tags: ["Ivy League", "Urban", "New York City", "Journalism"],
  },
  {
    id: "uchicago",
    name: "University of Chicago",
    location: "Chicago, IL",
    city: "Chicago",
    state: "IL",
    type: "private",
    ranking: 13,
    rating: 4.7,
    tuition: 61179,
    acceptanceRate: 0.07,
    enrollment: 18452,
    founded: 1890,
    satRange: [1500, 1580],
    color: "#800000",
    description: "Known for its rigorous academics and the Chicago School of economics, UChicago pushes students to question everything.",
    programs: ["Economics", "Mathematics", "Philosophy", "Statistics", "Law"],
    tags: ["Research", "Rigorous", "Urban", "Economics"],
  },
  {
    id: "upenn",
    name: "University of Pennsylvania",
    location: "Philadelphia, PA",
    city: "Philadelphia",
    state: "PA",
    type: "private",
    ranking: 7,
    rating: 4.7,
    tuition: 61710,
    acceptanceRate: 0.07,
    enrollment: 26543,
    founded: 1740,
    satRange: [1470, 1560],
    color: "#011F5B",
    description: "An Ivy League university famous for Wharton School of Business and its interdisciplinary approach to education.",
    programs: ["Business", "Nursing", "Engineering", "Law", "Medicine"],
    tags: ["Ivy League", "Business", "Urban", "Interdisciplinary"],
  },
  {
    id: "caltech",
    name: "California Institute of Technology",
    location: "Pasadena, CA",
    city: "Pasadena",
    state: "CA",
    type: "private",
    ranking: 9,
    rating: 4.8,
    tuition: 58680,
    acceptanceRate: 0.03,
    enrollment: 2233,
    founded: 1891,
    satRange: [1530, 1590],
    color: "#FF6C0C",
    description: "A small but world-leading science and engineering institution known for NASA's Jet Propulsion Laboratory.",
    programs: ["Physics", "Mathematics", "Engineering", "Chemistry", "Computer Science"],
    tags: ["STEM", "Research", "Small Campus", "Science"],
  },
  {
    id: "duke",
    name: "Duke University",
    location: "Durham, NC",
    city: "Durham",
    state: "NC",
    type: "private",
    ranking: 10,
    rating: 4.6,
    tuition: 60488,
    acceptanceRate: 0.07,
    enrollment: 17343,
    founded: 1838,
    satRange: [1470, 1560],
    color: "#003087",
    description: "A top research university known for its medical center, law school, and fierce basketball tradition.",
    programs: ["Medicine", "Law", "Public Policy", "Engineering", "Business"],
    tags: ["Research", "Sports", "Medical", "Southern"],
  },
  {
    id: "ucla",
    name: "UCLA",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    state: "CA",
    type: "public",
    ranking: 15,
    rating: 4.5,
    tuition: 13240,
    acceptanceRate: 0.09,
    enrollment: 46430,
    founded: 1919,
    satRange: [1290, 1510],
    color: "#2774AE",
    description: "A world-class public research university in Los Angeles, with strengths in film, medicine, and engineering.",
    programs: ["Film", "Medicine", "Engineering", "Business", "Law"],
    tags: ["Public Ivy", "Urban", "Diversity", "Hollywood"],
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    location: "Evanston, IL",
    city: "Evanston",
    state: "IL",
    type: "private",
    ranking: 11,
    rating: 4.6,
    tuition: 60768,
    acceptanceRate: 0.07,
    enrollment: 22603,
    founded: 1851,
    satRange: [1460, 1560],
    color: "#4E2A84",
    description: "A highly selective research university on the shores of Lake Michigan, known for journalism, law, and medicine.",
    programs: ["Journalism", "Law", "Medicine", "Engineering", "Music"],
    tags: ["Research", "Journalism", "Arts", "Lakeside"],
  },
  {
    id: "michigan",
    name: "University of Michigan",
    location: "Ann Arbor, MI",
    city: "Ann Arbor",
    state: "MI",
    type: "public",
    ranking: 23,
    rating: 4.4,
    tuition: 15948,
    acceptanceRate: 0.20,
    enrollment: 47907,
    founded: 1817,
    satRange: [1360, 1530],
    color: "#00274C",
    description: "A flagship public research university with top programs in business, engineering, and medicine.",
    programs: ["Engineering", "Business", "Medicine", "Law", "Architecture"],
    tags: ["Public Ivy", "Big Ten", "Research", "Sports"],
  },
  {
    id: "gatech",
    name: "Georgia Tech",
    location: "Atlanta, GA",
    city: "Atlanta",
    state: "GA",
    type: "public",
    ranking: 33,
    rating: 4.3,
    tuition: 12682,
    acceptanceRate: 0.17,
    enrollment: 44015,
    founded: 1885,
    satRange: [1350, 1530],
    color: "#B3A369",
    description: "A leading STEM-focused public research university with strong industry connections in the Southeast.",
    programs: ["Computer Science", "Engineering", "Business", "Architecture", "Sciences"],
    tags: ["STEM", "Research", "Southern", "Affordable"],
  },
  {
    id: "nyu",
    name: "New York University",
    location: "New York, NY",
    city: "New York",
    state: "NY",
    type: "private",
    ranking: 35,
    rating: 4.2,
    tuition: 58168,
    acceptanceRate: 0.12,
    enrollment: 51848,
    founded: 1831,
    satRange: [1340, 1530],
    color: "#57068C",
    description: "A global network university located in the heart of New York City, offering unmatched industry access.",
    programs: ["Business", "Law", "Medicine", "Arts", "Film"],
    tags: ["Urban", "Global", "Arts & Culture", "New York City"],
  },
  {
    id: "ut-austin",
    name: "UT Austin",
    location: "Austin, TX",
    city: "Austin",
    state: "TX",
    type: "public",
    ranking: 38,
    rating: 4.2,
    tuition: 11698,
    acceptanceRate: 0.31,
    enrollment: 51832,
    founded: 1883,
    satRange: [1230, 1480],
    color: "#BF5700",
    description: "The flagship of the UT System, offering strong programs in business, engineering, and liberal arts in vibrant Austin.",
    programs: ["Business", "Engineering", "Liberal Arts", "Natural Sciences", "Law"],
    tags: ["Affordable", "Big State", "Sports", "Southern"],
  },
  {
    id: "unc",
    name: "UNC Chapel Hill",
    location: "Chapel Hill, NC",
    city: "Chapel Hill",
    state: "NC",
    type: "public",
    ranking: 28,
    rating: 4.3,
    tuition: 9018,
    acceptanceRate: 0.18,
    enrollment: 32006,
    founded: 1789,
    satRange: [1310, 1490],
    color: "#4B9CD3",
    description: "The flagship public university of North Carolina, one of the most affordable top-ranked schools in the country.",
    programs: ["Journalism", "Public Health", "Business", "Medicine", "Law"],
    tags: ["Affordable", "Public Ivy", "Southern", "Sports"],
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    location: "Nashville, TN",
    city: "Nashville",
    state: "TN",
    type: "private",
    ranking: 18,
    rating: 4.5,
    tuition: 59290,
    acceptanceRate: 0.09,
    enrollment: 13892,
    founded: 1873,
    satRange: [1490, 1570],
    color: "#866D4B",
    description: "A research university in Nashville known for its medical center and strong humanities and engineering programs.",
    programs: ["Medicine", "Education", "Engineering", "Music", "Law"],
    tags: ["Research", "Medical", "Southern", "Music City"],
  },
  {
    id: "rice",
    name: "Rice University",
    location: "Houston, TX",
    city: "Houston",
    state: "TX",
    type: "private",
    ranking: 17,
    rating: 4.6,
    tuition: 52009,
    acceptanceRate: 0.09,
    enrollment: 7516,
    founded: 1912,
    satRange: [1490, 1580],
    color: "#002469",
    description: "A small research university known for its intimate community, strong sciences, and proximity to the NASA Space Center.",
    programs: ["Engineering", "Physics", "Music", "Architecture", "Computer Science"],
    tags: ["STEM", "Small Campus", "Southern", "Research"],
  },
];

// Derived helpers
export const ALL_PROGRAMS = Array.from(
  new Set(MOCK_COLLEGES.flatMap((c) => c.programs))
).sort();

export const ALL_STATES = Array.from(
  new Set(MOCK_COLLEGES.map((c) => c.state))
).sort();

export const TUITION_MAX = Math.max(...MOCK_COLLEGES.map((c) => c.tuition));
